import { toast } from '../utils/helpers.js';

export function downloadReport() {
  const blob = new Blob(
    [`ECOMATCH IMPACT REPORT\n\nWaste diverted: 42.8 kg\nCO2 avoided: 31.2 kg\nValue generated: Rp184.500\nWater saved: 1,820 L\n\nGenerated by EcoMatch prototype.`],
    { type: "text/plain" }
  );

  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "EcoMatch-Impact-Report.txt";
  a.click();
  URL.revokeObjectURL(a.href);

  toast("Impact report dibuat.");
}